import { SlidersHorizontal } from "lucide-react";
import { getTenantContextForModule } from "@/lib/platform/tenant-context";
import {
  addGenericWorkflowStageAction,
  createGenericWorkflowDefinitionAction,
  deleteGenericWorkflowStageAction,
  deleteProcessWorkflowStage,
  publishGenericWorkflowDefinitionAction,
  saveProcessType,
  saveProcessWorkflowStage,
  saveSubject,
} from "./actions";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";

export const dynamic = "force-dynamic";

function Checkbox({ name, defaultChecked, label }: { name: string; defaultChecked: boolean; label: string }) {
  return <label className="flex items-center gap-2 text-xs text-slate-600"><input name={name} type="checkbox" defaultChecked={defaultChecked} />{label}</label>;
}

function TypeFields({ type, departments }: { type?: { id: string; name: string; description: string | null; initialDepartmentId: string | null; defaultSlaDays: number | null; defaultPriority: string | null; isActive: boolean; requiresInterested: boolean; allowsInternalOpening: boolean; genericWorkflowEnabled: boolean }; departments: { id: string; name: string }[] }) {
  return <>
    {type && <input type="hidden" name="id" value={type.id} />}
    <input name="name" required defaultValue={type?.name} placeholder="Nome" className="rounded-lg border px-3 py-2 text-sm" />
    <input name="description" defaultValue={type?.description || ""} placeholder="Descrição" className="rounded-lg border px-3 py-2 text-sm" />
    <select name="initialDepartmentId" defaultValue={type?.initialDepartmentId || ""} className="rounded-lg border px-3 py-2 text-sm"><option value="">Setor inicial não definido</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select>
    <input name="defaultSlaDays" type="number" min="1" defaultValue={type?.defaultSlaDays || ""} placeholder="SLA em dias" className="rounded-lg border px-3 py-2 text-sm" />
    <select name="defaultPriority" defaultValue={type?.defaultPriority || ""} className="rounded-lg border px-3 py-2 text-sm"><option value="">Prioridade padrão</option><option>Normal</option><option>Alta</option><option>Urgente</option></select>
    <div className="flex flex-wrap items-center gap-3"><Checkbox name="isActive" defaultChecked={type?.isActive ?? true} label="Ativo" /><Checkbox name="requiresInterested" defaultChecked={type?.requiresInterested ?? false} label="Exige interessado" /><Checkbox name="allowsInternalOpening" defaultChecked={type?.allowsInternalOpening ?? true} label="Permite abertura interna" /><Checkbox name="genericWorkflowEnabled" defaultChecked={type?.genericWorkflowEnabled ?? false} label="Novo fluxo genérico versionado" /></div>
  </>;
}

export default async function ProcessosConfiguracaoPage() {
  const { prisma } = await getTenantContextForModule("CONFIGURACOES");
  const [types, departments, legacyStages, definitions, documentClasses] = await Promise.all([
    prisma.processType.findMany({ include: { subjects: { orderBy: { name: "asc" } }, initialDepartment: true }, orderBy: { name: "asc" } }),
    prisma.department.findMany({ where: { isActive: true }, select: { id: true, name: true }, orderBy: { name: "asc" } }),
    prisma.processWorkflowStage.findMany({ include: { processType: true, subject: true, department: true }, orderBy: [{ processType: { name: "asc" } }, { subjectId: "asc" }, { position: "asc" }] }),
    prisma.genericProcessWorkflowDefinition.findMany({ include: { processType: true, stages: { include: { department: true, requiredDocumentClass: true }, orderBy: { position: "asc" } } }, orderBy: [{ processType: { name: "asc" } }, { version: "desc" }] }),
    prisma.documentClass.findMany({ where: { isActive: true }, select: { id: true, label: true }, orderBy: { label: "asc" } }),
  ]);
  const optInTypes = types.filter((type) => type.genericWorkflowEnabled);
  const draftDefinitions = definitions.filter((definition) => definition.status === "DRAFT");

  return <PageFrame className="max-w-6xl space-y-4 px-1 py-1 md:px-2">
    <PageHeader title="Tipos e Assuntos de Processo" icon={<SlidersHorizontal className="size-4 shrink-0 text-indigo-600 dark:text-indigo-300" />} className="dark:border-slate-700 dark:bg-slate-800 dark:[&>h1]:text-white" />
    <p className="text-sm text-slate-500 dark:text-slate-400">O fluxo genérico é opt-in para novos tipos; configurações e processos legados permanecem inalterados.</p>

    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-semibold text-slate-800">Novo Tipo de Processo</h2><form action={saveProcessType} className="grid gap-3 md:grid-cols-3"><TypeFields departments={departments} /><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white md:col-span-3">Adicionar Tipo</button></form></section>

    <section className="space-y-4"><h2 className="font-semibold text-slate-800">Tipos cadastrados e Assuntos</h2>{types.map((type) => <div key={type.id} className="rounded-xl border border-slate-200 bg-white p-5"><form action={saveProcessType} className="grid gap-3 md:grid-cols-3"><TypeFields type={type} departments={departments} /><button className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 md:col-span-3">Salvar Tipo</button></form><div className="mt-5 border-t pt-4"><p className="mb-3 text-sm font-semibold text-slate-700">Assuntos</p><div className="space-y-3">{type.subjects.map((subject) => <form key={subject.id} action={saveSubject} className="grid gap-2 md:grid-cols-4"><input type="hidden" name="id" value={subject.id} /><input type="hidden" name="processTypeId" value={type.id} /><input name="name" required defaultValue={subject.name} className="rounded-lg border px-3 py-2 text-sm" /><input name="description" defaultValue={subject.description || ""} placeholder="Descrição" className="rounded-lg border px-3 py-2 text-sm" /><input name="slaDays" type="number" min="1" defaultValue={subject.slaDays || ""} placeholder="SLA em dias" className="rounded-lg border px-3 py-2 text-sm" /><button className="rounded-lg border px-3 py-2 text-sm font-semibold text-slate-700">Salvar assunto</button></form>)}<form action={saveSubject} className="grid gap-2 md:grid-cols-4"><input type="hidden" name="processTypeId" value={type.id} /><input name="name" required placeholder="Novo assunto" className="rounded-lg border px-3 py-2 text-sm" /><input name="description" placeholder="Descrição" className="rounded-lg border px-3 py-2 text-sm" /><input name="slaDays" type="number" min="1" placeholder="SLA em dias" className="rounded-lg border px-3 py-2 text-sm" /><button className="rounded-lg border px-3 py-2 text-sm font-semibold text-slate-700">Adicionar assunto</button></form></div></div></div>)}</section>

    <section className="rounded-xl border border-indigo-200 bg-indigo-50/40 p-5"><h2 className="font-semibold text-slate-800">Fluxo Genérico Versionado</h2><p className="mt-1 text-sm text-slate-600">Publique uma versão imutável. A abertura fixa a versão, o fuso da instância e o SLA em dias corridos; não há prazo manual.</p><form action={createGenericWorkflowDefinitionAction} className="mt-4 flex flex-wrap gap-3"><select name="processTypeId" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Novo tipo opt-in</option>{optInTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Criar rascunho de versão</button></form>{!optInTypes.length && <p className="mt-3 text-sm text-slate-500">Nenhum novo tipo foi marcado para o fluxo genérico.</p>}
      <div className="mt-5 space-y-4">{definitions.map((definition) => <div key={definition.id} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-semibold text-slate-800">{definition.processType.name} · versão {definition.version} <span className="text-xs text-slate-500">{definition.status}</span></p>{definition.status === "DRAFT" && <form action={publishGenericWorkflowDefinitionAction}><input type="hidden" name="definitionId" value={definition.id} /><button className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">Publicar versão</button></form>}</div><div className="mt-3 space-y-2">{definition.stages.map((stage) => <div key={stage.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-2 text-sm"><span>{stage.position}. {stage.label} · {stage.department.name} · {stage.slaCalendarDays} dia(s){stage.requiresSignedDocument ? ` · documento assinado: ${stage.requiredDocumentClass?.label || "classe ausente"}` : ""}</span>{definition.status === "DRAFT" && <form action={deleteGenericWorkflowStageAction}><input type="hidden" name="id" value={stage.id} /><button className="text-xs font-semibold text-red-700">Excluir</button></form>}</div>)}</div></div>)}{!definitions.length && <p className="text-sm text-slate-500">Nenhuma versão genérica criada.</p>}</div>
      {draftDefinitions.map((definition) => <form key={`stage-${definition.id}`} action={addGenericWorkflowStageAction} className="mt-4 grid gap-3 rounded-lg border border-dashed border-indigo-300 bg-white p-4 md:grid-cols-3"><input type="hidden" name="definitionId" value={definition.id} /><p className="md:col-span-3 text-sm font-semibold text-slate-700">Adicionar etapa ao rascunho {definition.processType.name} · versão {definition.version}</p><input name="position" required type="number" min="1" placeholder="Posição" className="rounded-lg border px-3 py-2 text-sm" /><input name="label" required placeholder="Nome da etapa" className="rounded-lg border px-3 py-2 text-sm" /><select name="departmentId" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Setor</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><input name="slaCalendarDays" required type="number" min="1" placeholder="SLA em dias corridos" className="rounded-lg border px-3 py-2 text-sm" /><select name="requiredDocumentClassId" className="rounded-lg border px-3 py-2 text-sm"><option value="">Classe de documento (se exigida)</option>{documentClasses.map((documentClass) => <option key={documentClass.id} value={documentClass.id}>{documentClass.label}</option>)}</select><label className="flex items-center gap-2 text-sm text-slate-600"><input name="requiresSignedDocument" type="checkbox" />Exige documento FINAL e SIGNED vinculado ao processo</label><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white md:col-span-3">Adicionar etapa</button></form>)}</section>

    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-800">Fluxo Legado por Tipo e Assunto</h2><p className="mt-1 text-sm text-slate-500">Mantido para tipos existentes. Não é usado pelo fluxo genérico versionado.</p><form action={saveProcessWorkflowStage} className="mt-4 grid gap-3 md:grid-cols-3"><select name="processTypeId" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Tipo de processo</option>{types.filter((type) => !type.genericWorkflowEnabled).map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><select name="subjectId" className="rounded-lg border px-3 py-2 text-sm"><option value="">Fluxo geral do tipo</option>{types.filter((type) => !type.genericWorkflowEnabled).flatMap((type) => type.subjects.map((subject) => <option key={subject.id} value={subject.id}>{type.name}: {subject.name}</option>))}</select><select name="departmentId" required className="rounded-lg border px-3 py-2 text-sm"><option value="">Setor da etapa</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><input name="position" type="number" min="1" required placeholder="Ordem" className="rounded-lg border px-3 py-2 text-sm" /><input name="slaDays" type="number" min="1" placeholder="SLA da etapa (dias)" className="rounded-lg border px-3 py-2 text-sm" /><input name="label" placeholder="Nome da etapa" className="rounded-lg border px-3 py-2 text-sm" /><label className="flex items-center gap-2 text-sm text-slate-600"><input name="isActive" type="checkbox" defaultChecked />Etapa ativa</label><button className="rounded-lg bg-slate-700 px-4 py-2 text-sm font-semibold text-white md:col-span-2">Adicionar etapa legada</button></form><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-3 py-2">Fluxo</th><th className="px-3 py-2">Etapa</th><th className="px-3 py-2">Setor</th><th className="px-3 py-2">SLA</th><th className="px-3 py-2" /></tr></thead><tbody>{legacyStages.map((stage) => <tr key={stage.id} className="border-t"><td className="px-3 py-2">{stage.processType.name}{stage.subject ? ` / ${stage.subject.name}` : ""}</td><td className="px-3 py-2">{stage.position}. {stage.label || "Sem nome"}</td><td className="px-3 py-2">{stage.department.name}</td><td className="px-3 py-2">{stage.slaDays ? `${stage.slaDays} dias` : "Sem SLA"}</td><td className="px-3 py-2 text-right"><form action={deleteProcessWorkflowStage}><input type="hidden" name="id" value={stage.id} /><button className="text-xs font-semibold text-red-700">Excluir</button></form></td></tr>)}</tbody></table></div></section>
  </PageFrame>;
}
