"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ErpPagination } from "@/components/app-ui/erp/ErpPagination";
import { definitionKinds } from "@/lib/obras/construction-rules";
import { publishConstructionDefinition, publishConstructionDistribution, publishConstructionZone, linkConstructionPropertyZone } from "../rules-actions";

type Option = { id: string; name: string };
type Definition = { fields: { key: string; label: string; type: "TEXT" | "NUMBER" | "DATE" | "CHOICE"; required: boolean; options: string[] }[]; checks: { key: string; label: string; required: boolean }[]; documents: { label: string; required: boolean }[] };
type Props = { tab: string; kind: keyof typeof definitionKinds; page: number; total: number; canManage: boolean; rows: { id: string; name: string; version: number; summary: string; date: string }[]; definition: Definition; purposes: Option[]; properties: Option[]; zoneOptions: Option[]; departments: Option[]; employees: (Option & { departmentId: string | null })[] };
const field = "h-8 w-full rounded border bg-white px-2 text-sm dark:bg-slate-900";

export default function ConstructionRulesClient({ tab, kind, page, total, canManage, rows, definition, purposes, properties, zoneOptions, departments, employees }: Props) {
  const router = useRouter();
  const [data, setData] = useState(definition);
  const [distribution, setDistribution] = useState({ departmentId: departments[0]?.id || "", strategy: "SECTOR", employeeId: "" });
  const [zone, setZone] = useState({ code: "", name: "", legalBasis: "", startsAt: "", endsAt: "", allowedPurposeIds: [] as string[], allowedCategories: ["BUILDING"] as string[], minimumLandArea: "0", maxFloorAreaRatio: "1", automatic: false });
  const [binding, setBinding] = useState({ realEstateId: "", zoneId: "" });
  const [pending, setPending] = useState(false);
  const [message, setMessage] = useState("");
  const href = (target: number) => `?${new URLSearchParams({ tab, kind, page: String(target) })}`;
  async function submit(event: React.FormEvent<HTMLFormElement>, operation: "definition" | "distribution" | "zone" | "binding") {
    event.preventDefault(); setPending(true); setMessage("");
    try {
      const result = operation === "definition" ? await publishConstructionDefinition({ kind, definition: data }) : operation === "distribution" ? await publishConstructionDistribution(distribution) : operation === "zone" ? await publishConstructionZone(zone) : await linkConstructionPropertyZone(binding);
      if (result.error) { setMessage(result.error); return; }
      setMessage(operation === "binding" ? "Zoneamento vinculado ao imóvel." : "Nova versão publicada, preservando as anteriores."); router.refresh();
    } catch { setMessage("Falha de comunicação. Tente novamente."); } finally { setPending(false); }
  }
  return <div className="space-y-3"><div className="flex flex-wrap gap-3 text-xs"><Link href="?tab=definitions" className="text-blue-700 underline">Formulários e checklists</Link><Link href="?tab=zones" className="text-blue-700 underline">Zoneamento</Link><Link href="?tab=distribution" className="text-blue-700 underline">Distribuição</Link></div>
    {message && <p role="status" className="rounded border p-2 text-sm">{message}</p>}
    {tab === "definitions" && <>
      <form method="GET" className="flex gap-2"><input type="hidden" name="tab" value={tab} /><select name="kind" defaultValue={kind} aria-label="Etapa" className={field}>{Object.entries(definitionKinds).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select><button className="rounded bg-blue-600 px-3 text-xs text-white">Selecionar</button></form>
      <form onSubmit={(event) => submit(event, "definition")} className="space-y-3 rounded-lg border p-3"><fieldset disabled={pending || !canManage} className="space-y-3">
        <h2 className="text-sm font-semibold">Campos adicionais — {definitionKinds[kind]}</h2>
        {data.fields.map((entry,index) => <div key={index} className="grid gap-2 rounded border p-2 sm:grid-cols-3"><label className="text-xs">Chave<input required className={field} value={entry.key} onChange={(event) => setData({ ...data, fields: data.fields.map((row,i) => i === index ? { ...row, key: event.target.value } : row) })} /></label><label className="text-xs">Rótulo<input required className={field} value={entry.label} onChange={(event) => setData({ ...data, fields: data.fields.map((row,i) => i === index ? { ...row, label: event.target.value } : row) })} /></label><label className="text-xs">Tipo<select className={field} value={entry.type} onChange={(event) => setData({ ...data, fields: data.fields.map((row,i) => i === index ? { ...row, type: event.target.value as typeof entry.type } : row) })}><option value="TEXT">Texto</option><option value="NUMBER">Número</option><option value="DATE">Data</option><option value="CHOICE">Seleção</option></select></label>{entry.type === "CHOICE" && <label className="text-xs sm:col-span-3">Opções (uma por linha)<textarea rows={3} className="w-full rounded border bg-transparent p-2 text-sm" value={entry.options.join("\n")} onChange={(event) => setData({ ...data, fields: data.fields.map((row,i) => i === index ? { ...row, options: event.target.value.split("\n") } : row) })} /></label>}<label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={entry.required} onChange={(event) => setData({ ...data, fields: data.fields.map((row,i) => i === index ? { ...row, required: event.target.checked } : row) })} />Obrigatório</label><button type="button" className="text-left text-xs text-red-700 underline" onClick={() => setData({ ...data, fields: data.fields.filter((_,i) => i !== index) })}>Remover campo</button></div>)}
        <button type="button" disabled={data.fields.length >= 50} className="text-xs text-blue-700 underline" onClick={() => setData({ ...data, fields: [...data.fields, { key: "", label: "", type: "TEXT", required: false, options: [] }] })}>Adicionar campo</button>
        <h2 className="text-sm font-semibold">Critérios para deferimento</h2>{data.checks.map((entry,index) => <div key={index} className="grid gap-2 sm:grid-cols-[8rem_1fr_auto_auto]"><input aria-label="Chave do critério" required placeholder="Chave" className={field} value={entry.key} onChange={(event) => setData({ ...data, checks: data.checks.map((row,i) => i === index ? { ...row, key: event.target.value } : row) })} /><input aria-label="Descrição do critério" required placeholder="Descrição" className={field} value={entry.label} onChange={(event) => setData({ ...data, checks: data.checks.map((row,i) => i === index ? { ...row, label: event.target.value } : row) })} /><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={entry.required} onChange={(event) => setData({ ...data, checks: data.checks.map((row,i) => i === index ? { ...row, required: event.target.checked } : row) })} />Obrigatório</label><button type="button" aria-label="Remover critério" onClick={() => setData({ ...data, checks: data.checks.filter((_,i) => i !== index) })}>×</button></div>)}<button type="button" disabled={data.checks.length >= 100} className="text-xs text-blue-700 underline" onClick={() => setData({ ...data, checks: [...data.checks, { key: "", label: "", required: true }] })}>Adicionar critério</button>
        <h2 className="text-sm font-semibold">Documentos da etapa</h2>{data.documents.map((entry,index) => <div key={index} className="flex gap-2"><input aria-label="Nome do documento" required className={field} value={entry.label} onChange={(event) => setData({ ...data, documents: data.documents.map((row,i) => i === index ? { ...row, label: event.target.value } : row) })} /><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={entry.required} onChange={(event) => setData({ ...data, documents: data.documents.map((row,i) => i === index ? { ...row, required: event.target.checked } : row) })} />Obrigatório</label><button type="button" aria-label="Remover documento" onClick={() => setData({ ...data, documents: data.documents.filter((_,i) => i !== index) })}>×</button></div>)}<button type="button" disabled={data.documents.length >= 50} className="text-xs text-blue-700 underline" onClick={() => setData({ ...data, documents: [...data.documents, { label: "", required: true }] })}>Adicionar documento</button>
        {canManage && <div className="text-right"><button disabled={pending} className="rounded bg-blue-600 px-3 py-2 text-xs text-white">Publicar nova versão</button></div>}
      </fieldset></form>
    </>}
    {tab === "distribution" && <form onSubmit={(event) => submit(event, "distribution")} className="rounded-lg border p-3"><fieldset disabled={pending || !canManage} className="grid gap-3 sm:grid-cols-3"><label className="text-xs">Setor<select required className={field} value={distribution.departmentId} onChange={(event) => setDistribution({ ...distribution, departmentId: event.target.value, employeeId: "" })}><option value="">Selecione</option>{departments.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label className="text-xs">Distribuição<select className={field} value={distribution.strategy} onChange={(event) => setDistribution({ ...distribution, strategy: event.target.value })}><option value="SECTOR">Ao setor</option><option value="USER">Usuário específico</option><option value="MANAGER">Gestor vigente</option><option value="LOWEST_LOAD">Analista com menor demanda</option></select></label>{distribution.strategy === "USER" && <label className="text-xs">Analista<select required className={field} value={distribution.employeeId} onChange={(event) => setDistribution({ ...distribution, employeeId: event.target.value })}><option value="">Selecione</option>{employees.filter((option) => option.departmentId === distribution.departmentId).map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}{canManage && <div className="text-right sm:col-span-3"><button disabled={pending} className="rounded bg-blue-600 px-3 py-2 text-xs text-white">Publicar estratégia</button></div>}</fieldset></form>}
    {tab === "zones" && <>
      <form onSubmit={(event) => submit(event, "zone")} className="rounded-lg border p-3"><fieldset disabled={pending || !canManage} className="grid gap-3 sm:grid-cols-2"><h2 className="text-sm font-semibold sm:col-span-2">Publicar regra de zoneamento</h2>{([['code','Código'],['name','Nome'],['legalBasis','Base legal / referência do plano diretor'],['minimumLandArea','Área mínima do terreno (m²)'],['maxFloorAreaRatio','Coeficiente máximo de aproveitamento']] as const).map(([key,label]) => <label key={key} className="text-xs">{label}<input required className={field} value={zone[key]} onChange={(event) => setZone({ ...zone, [key]: event.target.value })} /></label>)}<label className="text-xs">Início<input required type="date" className={field} value={zone.startsAt} onChange={(event) => setZone({ ...zone, startsAt: event.target.value })} /></label><label className="text-xs">Fim<input type="date" className={field} value={zone.endsAt} onChange={(event) => setZone({ ...zone, endsAt: event.target.value })} /></label><fieldset className="space-y-1 rounded border p-2"><legend className="text-xs">Finalidades permitidas</legend>{purposes.map((purpose) => <label key={purpose.id} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={zone.allowedPurposeIds.includes(purpose.id)} onChange={(event) => setZone({ ...zone, allowedPurposeIds: event.target.checked ? [...zone.allowedPurposeIds, purpose.id] : zone.allowedPurposeIds.filter((id) => id !== purpose.id) })} />{purpose.name}</label>)}</fieldset><fieldset className="space-y-1 rounded border p-2"><legend className="text-xs">Categorias permitidas</legend>{[['BUILDING','Obra'],['SUBDIVISION','Parcelamento']] .map(([key,label]) => <label key={key} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={zone.allowedCategories.includes(key)} onChange={(event) => setZone({ ...zone, allowedCategories: event.target.checked ? [...zone.allowedCategories, key] : zone.allowedCategories.filter((id) => id !== key) })} />{label}</label>)}</fieldset><label className="flex items-center gap-2 text-xs sm:col-span-2"><input type="checkbox" checked={zone.automatic} onChange={(event) => setZone({ ...zone, automatic: event.target.checked })} />Permitir avaliação automática dos parâmetros cadastrados</label>{canManage && <div className="text-right sm:col-span-2"><button disabled={pending} className="rounded bg-blue-600 px-3 py-2 text-xs text-white">Publicar zoneamento</button></div>}</fieldset></form>
      <form onSubmit={(event) => submit(event, "binding")} className="rounded-lg border p-3"><fieldset disabled={pending || !canManage} className="grid gap-3 sm:grid-cols-2"><h2 className="text-sm font-semibold sm:col-span-2">Vincular imóvel à versão urbanística</h2><label className="text-xs">Imóvel<select required className={field} value={binding.realEstateId} onChange={(event) => setBinding({ ...binding, realEstateId: event.target.value })}><option value="">Selecione</option>{properties.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label className="text-xs">Zoneamento<select required className={field} value={binding.zoneId} onChange={(event) => setBinding({ ...binding, zoneId: event.target.value })}><option value="">Selecione</option>{zoneOptions.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>{canManage && <div className="text-right sm:col-span-2"><button disabled={pending} className="rounded bg-blue-600 px-3 py-2 text-xs text-white">Vincular versão</button></div>}</fieldset></form>
    </>}
    <section className="rounded-lg border"><h2 className="border-b p-2 text-xs font-semibold">Histórico publicado</h2><table className="w-full table-fixed text-left text-xs"><thead className="bg-slate-100 text-[10px] uppercase text-slate-500 dark:bg-slate-800"><tr><th className="p-2">Registro</th><th className="w-16 p-2">Versão</th><th className="hidden p-2 sm:table-cell">Resumo</th><th className="w-24 p-2">Publicação</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="h-9 border-t"><td className="truncate p-2" title={row.name}>{row.name}</td><td className="p-2">{row.version}</td><td className="hidden truncate p-2 sm:table-cell" title={row.summary}>{row.summary}</td><td className="p-2">{row.date}</td></tr>)}</tbody></table>{!rows.length && <p className="p-5 text-center text-xs text-slate-500">Nenhuma versão publicada.</p>}<div className="border-t p-2"><ErpPagination page={page} total={total} pageSize={20} previousHref={href(page - 1)} nextHref={href(page + 1)} label="versões" /></div></section>
  </div>;
}
