-- MODELO: revise e remova os comentarios somente depois de substituir todos os
-- campos SUBSTITUA_* por dados oficiais de Ibema.
--
-- BEGIN;
--
-- INSERT INTO "Institution" (
--   "id", "name", "cnpj", "legalName", "address", "city", "state",
--   "zipCode", "phone", "email", "website", "createdAt", "updatedAt"
-- ) VALUES (
--   'ibema-institution',
--   'Prefeitura Municipal de Ibema',
--   'SUBSTITUA_CNPJ',
--   'Municipio de Ibema',
--   'SUBSTITUA_ENDERECO',
--   'Ibema',
--   'PR',
--   'SUBSTITUA_CEP',
--   'SUBSTITUA_TELEFONE',
--   'SUBSTITUA_EMAIL',
--   'SUBSTITUA_SITE',
--   CURRENT_TIMESTAMP,
--   CURRENT_TIMESTAMP
-- );
--
-- INSERT INTO "ConfiguracaoInstancia" (
--   "id", "nomePrefeitura", "cnpj", "municipio", "uf", "dominio",
--   "status", "createdAt", "updatedAt"
-- ) VALUES (
--   'ibema-instance',
--   'Prefeitura Municipal de Ibema',
--   'SUBSTITUA_CNPJ',
--   'Ibema',
--   'PR',
--   'SUBSTITUA_DOMINIO',
--   'Ativa',
--   CURRENT_TIMESTAMP,
--   CURRENT_TIMESTAMP
-- );
--
-- COMMIT;
