import Link from "next/link";
import { notFound } from "next/navigation";
import { HardHat } from "lucide-react";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";
import { getTenantContextForModule, canViewModule } from "@/lib/platform/tenant-context";
import { resolveConstructionAccess } from "@/lib/obras/construction-access";
import { areaKeys, areaLabels, constructionCaseWhere } from "@/lib/obras/construction-policy";
import { ErpPagination } from "@/components/app-ui/erp/ErpPagination";
import ConstructionViabilityClient from "./ConstructionViabilityClient";
import ConstructionReviewClient from "./ConstructionReviewClient";
import { definitionSchema } from "@/lib/obras/construction-rules";

export default async function ConstructionCasePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ page?: string; reviewPage?: string }> }) {
  const { id } = await params;
  const context = await getTenantContextForModule("OBRAS");
  const access = await resolveConstructionAccess(context);
  const item = await context.prisma.constructionCase.findFirst({ where: { AND: [{ id }, constructionCaseWhere(access)] }, include: { process: { select: { id: true, protocolNumber: true, status: true, description: true, person: { select: { fullName: true } }, company: { select: { corporateName: true } }, currentDepartment: { select: { name: true } } } }, configuration: true, properties: { select: { id: true, realEstateId: true, cadastralSnapshot: true } } } });
  if (!item) notFound();
  const query = await searchParams;
  const total = await context.prisma.constructionViabilityResult.count({ where: { caseId: item.id } });
  const page = Math.min(Math.max(1, Math.ceil(total / 20)), Math.max(1, Number.parseInt(query.page || "1", 10) || 1));
  const evaluations = await context.prisma.constructionViabilityResult.findMany({ where: { caseId: item.id }, select: { id: true, outcome: true, calculationSnapshot: true, createdAt: true }, orderBy: [{ createdAt: "desc" }, { id: "asc" }], skip: (page - 1) * 20, take: 20 });
  const reviewTotal = await context.prisma.constructionReview.count({ where: { caseId: item.id } });
  const reviewPage = Math.min(Math.max(1, Math.ceil(reviewTotal / 20)), Math.max(1, Number.parseInt(query.reviewPage || "1", 10) || 1));
  const [reviews, checklist, documents] = await Promise.all([
    context.prisma.constructionReview.findMany({ where: { caseId: item.id }, orderBy: [{ createdAt: "desc" }, { id: "asc" }], skip: (reviewPage - 1) * 20, take: 20 }),
    context.prisma.constructionDefinitionVersion.findFirst({ where: { kind: "PERMIT" }, orderBy: { version: "desc" } }),
    context.prisma.document.findMany({ where: { processDocuments: { some: { processId: item.process.id } }, status: { in: ["Válido", "Assinado"] }, versions: { some: { status: { in: ["FINAL", "SIGNED"] } } } }, select: { id: true, title: true }, orderBy: { title: "asc" } }),
  ]);
  return <PageFrame className="space-y-3 p-3"><PageHeader title={`Construção Civil — ${item.process.protocolNumber}`} icon={<HardHat className="size-4" />} />
    <div className="flex gap-3 text-xs"><Link href="/obras/construcao-civil" className="text-blue-700 underline">Voltar às solicitações</Link>{canViewModule(context.user, "PROCESSOS") && <Link href={`/protocolos/processos/${item.process.id}`} className="text-blue-700 underline">Abrir protocolo vinculado</Link>}</div>
    <section className="grid gap-2 rounded-lg border p-3 text-xs sm:grid-cols-2"><p><strong>Requerente:</strong> {item.process.person?.fullName || item.process.company?.corporateName}</p><p><strong>Setor responsável:</strong> {item.process.currentDepartment?.name || "—"}</p><p><strong>Situação do protocolo:</strong> {item.process.status}</p><p><strong>Categoria:</strong> {item.category === "BUILDING" ? "Obra" : "Parcelamento do solo"} — {item.locationType === "URBAN" ? "Urbana" : "Rural"}</p><p><strong>Modalidade:</strong> {item.regularization ? "Regularização" : "Normal"}</p><p><strong>Configuração preservada:</strong> v{item.configuration.version}</p><p className="whitespace-pre-wrap sm:col-span-2"><strong>Descrição:</strong> {item.process.description}</p></section>
    <section className="space-y-2 rounded-lg border p-3 text-xs"><h2 className="font-semibold">Áreas e memória de cálculo</h2><div className="grid gap-2 sm:grid-cols-5">{areaKeys.map((key) => <p key={key}><strong>{areaLabels[key]}:</strong> {item[key].toString()} m²</p>)}</div><p><strong>Total:</strong> {item.totalArea.toString()} m²</p><pre className="whitespace-pre-wrap break-words rounded bg-slate-50 p-2 text-[11px] text-slate-700">{JSON.stringify(item.calculationSnapshot, null, 2)}</pre></section>
    <section className="space-y-2 rounded-lg border p-3 text-xs"><h2 className="font-semibold">Classificações preservadas na abertura</h2><pre className="whitespace-pre-wrap break-words">{JSON.stringify(item.catalogSnapshot, null, 2)}</pre></section>
    <section className="space-y-2 rounded-lg border p-3 text-xs"><h2 className="font-semibold">Campos adicionais preservados</h2><pre className="whitespace-pre-wrap break-words">{JSON.stringify(item.additionalValues, null, 2)}</pre></section>
    <section className="space-y-3 rounded-lg border p-3"><h2 className="text-sm font-semibold">Análise e readequações</h2><p className="text-xs">Situação: {item.reviewStatus} — Revisão {item.revisionCount} — Franquia: {item.configuration.freeRevisions}{item.correctionDeadline ? ` — Prazo: ${item.correctionDeadline.toLocaleDateString("pt-BR")}` : ""}</p><ConstructionReviewClient key={`${item.revisionCount}:${item.reviewStatus}:${checklist?.version || 0}`} caseId={item.id} revision={item.revisionCount} status={item.reviewStatus} definitionVersion={checklist?.version || 0} definition={definitionSchema.parse(checklist?.definition || { fields: [], checks: [], documents: [] })} documents={documents} canReview={access.administrator || access.roles.some((role) => ["ANALYST", "MANAGER"].includes(role))} />{reviews.map((review) => <details key={review.id} className="rounded border p-2 text-xs"><summary className="cursor-pointer">{review.createdAt.toLocaleString("pt-BR")} — Revisão {review.revision} — {review.reviewType} — {review.decision}</summary><p className="mt-2 whitespace-pre-wrap">{review.notes}</p><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify({ checklist: review.definitionSnapshot, evidencias: review.evidenceSnapshot }, null, 2)}</pre></details>)}{!reviewTotal && <p className="text-xs text-slate-500">Nenhum parecer registrado.</p>}<ErpPagination page={reviewPage} total={reviewTotal} pageSize={20} previousHref={`?page=${page}&reviewPage=${reviewPage - 1}`} nextHref={`?page=${page}&reviewPage=${reviewPage + 1}`} label="pareceres" /></section>
    <section className="space-y-3 rounded-lg border p-3"><h2 className="text-sm font-semibold">Avaliações de parâmetros urbanísticos</h2><ConstructionViabilityClient caseId={item.id} canEvaluate={access.administrator || access.roles.some((role) => ["ANALYST", "MANAGER"].includes(role))} />{evaluations.map((evaluation) => <details key={evaluation.id} className="rounded border p-2 text-xs"><summary className="cursor-pointer">{evaluation.createdAt.toLocaleString("pt-BR")} — {evaluation.outcome === "APPROVED" ? "Parâmetros compatíveis" : evaluation.outcome === "DENIED" ? "Parâmetros incompatíveis" : "Análise técnica necessária"}</summary><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify(evaluation.calculationSnapshot, null, 2)}</pre></details>)}{!total && <p className="text-xs text-slate-500">Nenhuma avaliação registrada.</p>}<ErpPagination page={page} total={total} pageSize={20} previousHref={`?page=${page - 1}`} nextHref={`?page=${page + 1}`} label="avaliações" /></section>
    <section className="space-y-2 rounded-lg border p-3 text-xs"><h2 className="font-semibold">Imóveis — snapshot cadastral na abertura</h2>{item.properties.map((property) => <details key={property.id} className="rounded border p-2"><summary className="cursor-pointer">{property.realEstateId}</summary><pre className="mt-2 whitespace-pre-wrap break-words">{JSON.stringify(property.cadastralSnapshot, null, 2)}</pre></details>)}</section>
  </PageFrame>;
}
