"use server";
import { revalidatePath } from "next/cache";
import { getTenantContextForModuleOperation } from "@/lib/platform/tenant-context";
import { advanceCemeteryProcess, attachCemeteryDocument, createCemetery, createCemeteryChapel, createCemeteryFeeRule, createCemeteryIdentificationField, createCemeteryLot, createCemeteryOssuary, createCemeteryProcess, createDeathCause, createGrave, createSector, enrollCemeteryFeeInDebt, grantConcession, issueCemeteryFee, registerDeceased, registerEmployee, registerFuneralHome, registerMovement, setCemeteryEntityActive } from "@/lib/tributacao/s9-service";
const path = "/cemiterios";
const done = (error?: unknown) => ({ error: error instanceof Error ? error.message : error ? "Não foi possível concluir a operação." : undefined });
async function ctx(operation: "create" | "update") { return getTenantContextForModuleOperation("CEMITERIOS", operation); }
const actor = (c: Awaited<ReturnType<typeof ctx>>) => ({ usuarioId: c.user.id });
export async function createCemeteryAction(input: Parameters<typeof createCemetery>[1]) { try { const c = await ctx("create"); await createCemetery(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createSectorAction(input: Parameters<typeof createSector>[1]) { try { const c = await ctx("create"); await createSector(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createGraveAction(input: Parameters<typeof createGrave>[2]) { try { const c = await ctx("create"); await createGrave(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function registerEmployeeAction(input: Parameters<typeof registerEmployee>[1]) { try { const c = await ctx("create"); await registerEmployee(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function registerFuneralHomeAction(input: Parameters<typeof registerFuneralHome>[1]) { try { const c = await ctx("create"); await registerFuneralHome(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function registerDeceasedAction(input: Omit<Parameters<typeof registerDeceased>[2], "deathDate" | "birthDate" | "scheduledAt"> & { deathDate: string; birthDate?: string; scheduledAt?: string }) { try { const c = await ctx("create"); await registerDeceased(c.prisma, actor(c), { ...input, deathDate: new Date(input.deathDate), birthDate: input.birthDate ? new Date(input.birthDate) : undefined, scheduledAt: input.scheduledAt ? new Date(input.scheduledAt) : undefined }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function registerMovementAction(input: Parameters<typeof registerMovement>[2]) { try { const c = await ctx("create"); await registerMovement(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function grantConcessionAction(input: Omit<Parameters<typeof grantConcession>[2], "endsAt"> & { endsAt?: string }) { try { const c = await ctx("create"); await grantConcession(c.prisma, actor(c), { ...input, endsAt: input.endsAt ? new Date(input.endsAt) : undefined }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function issueCemeteryFeeAction(input: { taxpayerId: string; amount?: number; dueDate: string; movementId?: string; concessionId?: string; feeRuleId?: string; quantity?: number }) { try { const c = await ctx("create"); await issueCemeteryFee(c.prisma, actor(c), { ...input, dueDate: new Date(input.dueDate), movementId: input.movementId || undefined, concessionId: input.concessionId || undefined, feeRuleId: input.feeRuleId || undefined }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function enrollCemeteryFeeInDebtAction(assessmentId: string) { try { const c = await ctx("create"); await enrollCemeteryFeeInDebt(c.prisma, actor(c), assessmentId); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createChapelAction(input: Parameters<typeof createCemeteryChapel>[1]) { try { const c = await ctx("create"); await createCemeteryChapel(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createOssuaryAction(input: Parameters<typeof createCemeteryOssuary>[1]) { try { const c = await ctx("create"); await createCemeteryOssuary(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createLotAction(input: Parameters<typeof createCemeteryLot>[2]) { try { const c = await ctx("create"); await createCemeteryLot(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createIdentificationFieldAction(input: Parameters<typeof createCemeteryIdentificationField>[1]) { try { const c = await ctx("create"); await createCemeteryIdentificationField(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createDeathCauseAction(input: Parameters<typeof createDeathCause>[1]) { try { const c = await ctx("create"); await createDeathCause(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function setEntityActiveAction(input: Parameters<typeof setCemeteryEntityActive>[2]) { try { const c = await ctx("update"); await setCemeteryEntityActive(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createProcessAction(input: Omit<Parameters<typeof createCemeteryProcess>[2], "scheduledAt"> & { scheduledAt: string }) { try { const c = await ctx("create"); await createCemeteryProcess(c.prisma, actor(c), { ...input, scheduledAt: new Date(input.scheduledAt) }); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function advanceProcessAction(input: Parameters<typeof advanceCemeteryProcess>[2]) { try { const c = await ctx("update"); await advanceCemeteryProcess(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function attachDocumentAction(input: Parameters<typeof attachCemeteryDocument>[2]) { try { const c = await ctx("create"); await attachCemeteryDocument(c.prisma, actor(c), input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
export async function createFeeRuleAction(input: Parameters<typeof createCemeteryFeeRule>[1]) { try { const c = await ctx("create"); await createCemeteryFeeRule(c.prisma, input); revalidatePath(path); return done(); } catch (e) { return done(e); } }
