import { KeyRound, ShieldCheck } from "lucide-react";
import { PageFrame } from "@/components/app-ui/PageFrame";
import { PageHeader } from "@/components/app-ui/PageHeader";
import { getTenantContextForModule, isSystemAdministrator } from "@/lib/platform/tenant-context";
import { registerCertificateAction, setCertificateStatusAction, signVersionWithA1Action } from "./actions";

export const dynamic = "force-dynamic";
const field = "h-9 w-full rounded border border-slate-300 bg-white px-3 text-sm";
const button = "rounded bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-50";

export default async function CertificatesPage() {
  const { prisma, user } = await getTenantContextForModule("CONFIGURACOES");
  if (!isSystemAdministrator(user)) return <PageFrame><PageHeader title="Certificados A1" icon={<KeyRound className="size-4" />} /><p className="rounded border bg-white p-4 text-sm">Acesso exclusivo do administrador do sistema.</p></PageFrame>;
  const [certificates, versions, audits] = await Promise.all([
    prisma.digitalCertificate.findMany({ orderBy: { createdAt: "desc" } }),
    prisma.documentVersion.findMany({ where: { status: "FINAL", document: { documentClass: { signaturePolicy: "ICP_REQUIRED" } } }, include: { document: true }, orderBy: { finalizedAt: "desc" }, take: 100 }),
    prisma.certificateUseAudit.findMany({ include: { certificate: { select: { alias: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const now = new Date();
  return <PageFrame className="space-y-3 px-1 py-1 md:px-2"><PageHeader title="Certificados A1" icon={<KeyRound className="size-4 text-slate-700" />} />
    <div className="rounded border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><b>Custódia segura:</b> esta tela nunca recebe chave privada ou senha. `credentialReference` identifica variáveis protegidas no ambiente do servidor: <code>REFERENCIA_PRIVATE_KEY_PEM</code> e, se necessário, <code>REFERENCIA_PRIVATE_KEY_PASSPHRASE</code>.</div>
    <div className="grid gap-3 xl:grid-cols-[420px_1fr]"><form action={registerCertificateAction} className="grid content-start gap-2 rounded border bg-white p-4"><h2 className="font-bold">Cadastrar metadados públicos</h2><input className={field} name="alias" placeholder="Alias" required /><input className={field} name="ownerName" placeholder="Titular / entidade" required /><input className={field} name="credentialReference" placeholder="Referência, ex.: IBEMA_A1" pattern="[A-Z][A-Z0-9_]{2,80}" required /><input className={field} name="purposes" defaultValue="GED" placeholder="Finalidades separadas por vírgula" /><textarea className={`${field} h-36 py-2 font-mono text-xs`} name="certificatePem" placeholder="Certificado público PEM" required /><textarea className={`${field} h-28 py-2 font-mono text-xs`} name="intermediatePems" placeholder="Intermediárias PEM; separe por ---CERTIFICATE---" /><textarea className={`${field} h-36 py-2 font-mono text-xs`} name="trustedRootPem" placeholder="Raiz confiável PEM" required /><button className={button}>Cadastrar certificado</button></form>
      <div className="grid content-start gap-3"><section className="rounded border bg-white p-4"><h2 className="flex items-center gap-2 font-bold"><ShieldCheck className="size-4" />Inventário</h2>{certificates.map((certificate) => <article key={certificate.id} className="mt-3 border-t pt-3 text-xs"><div className="flex flex-wrap items-start justify-between gap-2"><div><b>{certificate.alias}</b> · {certificate.ownerName}<p className={certificate.validTo < now ? "font-bold text-rose-700" : ""}>{certificate.validTo < now ? "EXPIRED" : certificate.status} · válido até {certificate.validTo.toLocaleDateString("pt-BR")}</p><p className="break-all font-mono text-[10px]">{certificate.fingerprint256}</p></div><form action={setCertificateStatusAction} className="flex gap-1"><input type="hidden" name="certificateId" value={certificate.id} /><select className={field} name="status" defaultValue={certificate.status}><option>ACTIVE</option><option>SUSPENDED</option><option>REVOKED</option></select><button className={button}>Aplicar</button></form></div></article>)}{!certificates.length && <p className="mt-2 text-xs text-slate-500">Nenhum certificado cadastrado.</p>}</section>
        <form action={signVersionWithA1Action} className="grid gap-2 rounded border bg-white p-4"><h2 className="font-bold">Assinar versão ICP_REQUIRED</h2><select className={field} name="documentVersionId" required><option value="">Documento final</option>{versions.map((version) => <option key={version.id} value={version.id}>{version.document.title} · versão {version.versionNumber}</option>)}</select><select className={field} name="certificateId" required><option value="">Certificado ativo</option>{certificates.filter((certificate) => certificate.status === "ACTIVE" && certificate.validFrom <= now && certificate.validTo >= now).map((certificate) => <option key={certificate.id} value={certificate.id}>{certificate.alias} · {certificate.ownerName}</option>)}</select><button className={button} disabled={!versions.length || !certificates.some((certificate) => certificate.status === "ACTIVE" && certificate.validFrom <= now && certificate.validTo >= now)}>Assinar hash da versão</button><p className="text-[10px] text-slate-500">Gera evidência criptográfica destacada vinculada ao hash imutável. Não declara PAdES nem altera visualmente o PDF.</p></form>
        <section className="rounded border bg-white p-4"><h2 className="font-bold">Auditoria de uso</h2>{audits.map((audit) => <p key={audit.id} className="border-t py-2 text-xs"><b>{audit.outcome}</b> · {audit.certificate?.alias ?? "sem certificado"} · {audit.purpose} · {audit.createdAt.toLocaleString("pt-BR")} {audit.errorCode ? `· ${audit.errorCode}` : ""}</p>)}</section></div></div>
  </PageFrame>;
}
